### ISSUE TITLE
ip() with POST method still returns null

### ISSUE THREAD

**Issue by KwaiTushan** [gaurishhs/elysia-ip#15]
- package.json
```ts
"dependencies": {
    "elysia": "latest",
    "elysia-ip": "latest",
    "minimist": "^1.2.8",
    "mongodb": "^6.5.0",
    "toolbx": "^1.0.8"
  },
```

- I've already updated
```shell
bun update v1.0.35 (940448d6)
  🔍 Resolving [1/6] warn: Slow filesystem detected. If /home/tsingkwai/.bun/install/cache is a network drive, consider setting $BUN_INSTALL_CACHE_DIR to a local folder.

 + elysia-ip@1.0.2

 1 package installed [1.70s]
```

- index.ts

```ts
const app = new Elysia()
  .use(ip())
  .get('/', () => `TransDataAPIserver VER ${main.version}`) // Send back server banner
// Load routers
Routers.forEach((obj) => {
  app.all(obj.path, async (contents: requestObject) => {
    try {
      const date = new Date();
      if (hasDebug) logger(`audit> ${date} => ${JSON.stringify(contents)}`, 4);
      switch (obj.authType) {
        case 'token':
          return await Gateway(contents, obj.isAdmin, (contents, userObject) => obj.handler(contents, userObject))
        case 'none':
        default:
          return await obj.handler(contents)
      }
    } catch (error) {
      let errMsg = String(error);
      if (error instanceof Error) {
        errMsg = error.message;
      }
      const result: resultObject = {
        succeed: false,
        msg: errMsg,
        data: undefined
      }
      return JSON.stringify(result)
    }
  }, obj.schema)
})
```

- type.ts

```ts
export interface requestObject {
    body: any
    query: Record<string, string | undefined>
    params: Record<string, string | undefined>
    headers: Record<string, string | undefined>
    response: resultObject
    path: string,
    ip?: {
        address: string;
        family: string;
        port: number;
    }
};
```

- Example contents

```
audit> Mon Apr 01 2024 21:10:31 GMT+0800 (Taipei Standard Time) => {"request":{},"store":{},"qi":-1,"path":"/api/manage/user/resetpassword","set":{"headers":{},"status":200,"cookie":{}},"headers":{"host":"127.0.0.1:9281","user-agent":"curl/8.2.1","accept":"*/*","content-type":"application/json","authorization":"Bearer 7ea72ae0d767ffa435a0f74fb073d5c4bcd0b40467ddff669140ce72a0dadd08","content-length":"48"},"cookie":{},"query":{},"body":{"password":"3125f36f28dac16c87c63e0f23a743eb"},"ip":null}
```

**Comment by KwaiTushan** [comment]
okay, i'll try to figure out the cause then

**Comment by KwaiTushan** [comment]
Gave up, i think i should just let caddy or nginx handle this feature

**Comment by gaurishhs** [comment]
You are correct, This issue occurs when there is body validation but it doesn't if it's just a plain POST request.

**Comment by gaurishhs** [comment]
I have published a new release containing a check for Headers only mode which should utilize headers passed by the reverse proxy. (`v1.0.3`)

**Comment by KwaiTushan** [comment]
Any idea/workaround for addressing this issue?

> You are correct, This issue occurs when there is body validation but it doesn't if it's just a plain POST request.

**Comment by w5b** [comment]
still experiencing this issue. using latest version of ban, elysia, and elysia-ip

**Comment by w5b** [comment]
for me it happens on any other requests than a get. i can only get the ip on get requests

**Comment by w5b** [comment]
still experience this issues on latest version of elysia-ip,  bun and elysia.

**Comment by kwaitsing** [comment]
> still experience this issues on latest version of elysia-ip, bun and elysia.

~~Be creative~~

A workaround here is to use front proxy like caddy
